[package]
name = "tatami"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["giraffekey <giraffekey@tutanota.com>"]

[dependencies]
image = "0.25"
itertools = "0.13"
noise = "0.9"
rand = "0.8"
rand_chacha = "0.3"
rayon = "1.10"
rustc-hash = "2.0"
strum = "0.26"
strum_macros = "0.26"
